# Site settings
title: Columbus Meetup
email: chrisyuska@gmail.com
description: >
  We're developers and designers striving to build a more stable entrepreneurial community in the Columbus, Ohio area.
url: "http://columbusmeetup.com" # the base hostname & protocol for your site
github_username:  ColumbusMeetup
timezone: America/New_York

# Build settings
markdown: kramdown
highlighter: pygments

# group settings
groups: snem
snem:
  title: Short North Entrepreneurial Meetup
  description: >
    Get some work done on your side project or startup and meet some other
    developers, designers, and entrepreneurs in the Columbus area in the process.
